<?php

use App\Models\ContentRecord;

ContentRecord::updateOrCreate(
    ['content_type' => 'home'],
    ['data' => [
        'hero' => ['images' => ['/images/hero/hero-1.jpg', '/images/hero/hero-2.jpg', '/images/hero/hero-3.jpg'], 'frame_image' => '/images/hero/frame.jpg', 'description' => 'Sekolah kejuruan favorit yang menyiapkan lulusan unggul, berkarakter, dan memiliki kompetensi tinggi sesuai kebutuhan industri masa depan.', 'accreditation' => 'Peringkat B', 'facility_title' => 'Fasilitas Modern', 'facility_description' => 'Mendukung penuh kompetensi siswa di era digital.'],
        'welcome' => ['image' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=800', 'principal_name' => 'Emma Sukmayati', 'principal_title' => 'Kepala SMKN 11 Kab. Tangerang', 'title' => 'Selamat Datang di Portal Resmi SMKN 11 Kabupaten Tangerang', 'paragraphs' => ['Puji syukur kita panjatkan ke hadirat Allah SWT atas rahmat dan karunia-Nya. Di era digitalisasi dan disrupsi teknologi saat ini, pendidikan vokasi memegang peran krusial dalam mencetak generasi muda yang tidak hanya kompeten, tetapi juga memiliki karakter dan daya adaptasi yang tinggi.', 'SMKN 11 Kabupaten Tangerang berkomitmen penuh untuk menjadi lembaga pendidikan yang inovatif, berdaya saing global, dan berakar pada nilai-nilai luhur bangsa. Melalui sinkronisasi kurikulum dengan industri, kami berupaya memastikan lulusan kami siap menghadapi tantangan dunia kerja masa depan.'], 'quote' => '"SMK BISA, SMK HEBAT, Vokasi Kuat Menguatkan Indonesia!"'],
        'about' => ['title' => 'Tentang SMKN 11 Kabupaten Tangerang', 'subtitle' => 'Sekolah vokasi yang menyiapkan lulusan unggul, kompeten, dan siap bersaing di dunia kerja.', 'paragraphs' => ['SMKN 11 Kabupaten Tangerang adalah lembaga pendidikan kejuruan negeri yang berdiri pada tahun 2013 dan berkomitmen mencetak siswa berprestasi, berakhlaqul karimah, dan memiliki kompetensi sesuai kebutuhan industri.', 'Berlokasi di Kp. Saradan, Desa Pangkat, Kecamatan Jayanti, sekolah ini memiliki 6 program keahlian unggulan dengan 1.124 siswa aktif dan 51 tenaga pengajar profesional yang berdedikasi.', 'Dengan akreditasi B dan didukung fasilitas laboratorium, bengkel, serta lingkungan belajar yang kondusif, lulusan kami tidak hanya siap bekerja, tetapi juga memiliki jiwa kewirausahaan dan akhlak mulia yang kuat.'], 'card_label' => 'Sekolah kami', 'card_title' => 'Lingkungan belajar yang memotivasi', 'quote' => '"Kami terus mendorong setiap siswa untuk tumbuh menjadi pribadi yang unggul, disiplin, dan siap memberikan kontribusi nyata bagi masyarakat dan bangsa."', 'location' => 'Kabupaten Tangerang, Banten'],
        'stats' => [['value' => '1.124+', 'label' => 'Siswa Aktif'], ['value' => '51+', 'label' => 'Tenaga Pengajar'], ['value' => '6', 'label' => 'Program Keahlian'], ['value' => '33', 'label' => 'Rombel']],
        'social' => ['instagram' => 'https://instagram.com/official_smkn11kab.tng', 'tiktok' => 'https://tiktok.com/@osis_smkn11kabtangeran', 'email' => 'smkn11kabtangschool@gmail.com'],
        'contact' => ['address' => "Kp. Saradan RT. 03/01, Desa Pangkat,\nKec. Jayanti, Kab. Tangerang, Banten 15610", 'phone' => '0812 9922 0831', 'email' => 'smkn11kabtangschool@gmail.com', 'hours' => 'Senin - Jumat, 07:00 - 15:00 WIB', 'map_query' => 'Kp. Saradan RT. 03/01, Pangkat, Jayanti, Kabupaten Tangerang, Banten 15610'],
    ]]
);

echo 'home content restored';
