<?php

namespace App\Services;

use App\Models\Guru;
use App\Models\OsisAccount;
use App\Models\Student;
use App\Models\User;
use Illuminate\Support\Str;

/**
 * Shared helpers for the account system (guru / siswa / OSIS):
 * resolving login identifiers, generating unique IDs and building the
 * combined profile payload used by auth, my-profile and admin endpoints.
 */
class AccountService
{
    /**
     * Resolve a login identifier (email, NIP, NUPTK, teacher_id, NISN or
     * member_id) to a user account, or null when not found.
     */
    public function resolveUser(string $identifier): ?User
    {
        $term = trim($identifier);

        if ($term === '') {
            return null;
        }

        if (str_contains($term, '@')) {
            return User::query()->where('email', strtolower($term))->first();
        }

        $guru = Guru::query()
            ->where('nip', $term)
            ->orWhere('nuptk', $term)
            ->orWhere('teacher_id', $term)
            ->first();

        if ($guru) {
            return User::query()->find($guru->id);
        }

        $osis = OsisAccount::query()
            ->where('member_id', $term)
            ->orWhere('nisn', $term)
            ->first();

        if ($osis) {
            return User::query()->find($osis->id);
        }

        $student = Student::query()->where('nisn', $term)->first();

        if ($student) {
            return User::query()->find($student->id);
        }

        return null;
    }

    /**
     * Normalize a gender value to the project's stored convention: 'L' / 'P'.
     */
    public function normalizeGender(mixed $value): string
    {
        $raw = strtolower(trim((string) $value));

        return match ($raw) {
            'l', 'm', 'pria', 'laki', 'laki-laki', 'laki laki', 'male' => 'L',
            'p', 'f', 'wanita', 'perempuan', 'female' => 'P',
            default => '',
        };
    }

    /**
     * Normalize a date into Y-m-d for the database, or null when empty/invalid.
     * Accepts DateTimeInterface, Excel/Sheets serial numbers, d/m/Y and ISO dates.
     */
    public function normalizeDate(mixed $value): ?string
    {
        if ($value instanceof \DateTimeInterface) {
            return $value->format('Y-m-d');
        }

        if ($value === null || $value === '') {
            return null;
        }

        $raw = trim((string) $value);
        if ($raw === '') {
            return null;
        }

        // Excel / Google Sheets serial number: days since 1899-12-30.
        if (is_numeric($raw)) {
            $serial = (float) $raw;
            if ($serial >= 20000 && $serial <= 80000) {
                $days = (int) floor($serial);

                return (new \DateTime('1899-12-30'))->modify('+'.$days.' days')->format('Y-m-d');
            }
        }

        // d/m/Y or d-m-Y (common Indonesian spreadsheet format).
        if (preg_match('#^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$#', $raw, $m)) {
            return sprintf('%04d-%02d-%02d', (int) $m[3], (int) $m[2], (int) $m[1]);
        }

        // ISO YYYY-MM-DD, optionally followed by time.
        $iso = preg_replace('#^(\d{4})-(\d{2})-(\d{2}).*$#', '$1-$2-$3', $raw);
        if (preg_match('#^\d{4}-\d{2}-\d{2}$#', (string) $iso)) {
            return $iso;
        }

        return null;
    }

    /**
     * Autogenerated student login email derived from NISN (kept as text).
     */
    public function studentEmail(string $nisn): string
    {
        return 'nisn-'.$nisn.'@mading.smkn11.sch.id';
    }

    public function generateTeacherId(): string
    {
        do {
            $id = 'GR'.strtoupper(Str::random(6));
        } while (Guru::query()->where('teacher_id', $id)->exists());

        return $id;
    }

    public function generateMemberId(): string
    {
        do {
            $id = 'OS'.strtoupper(Str::random(6));
        } while (OsisAccount::query()->where('member_id', $id)->exists());

        return $id;
    }

    /**
     * Build the combined profile payload (profile fields + role-specific data).
     */
    public function profilePayload(User $user): array
    {
        $profile = $user->profileRecord;

        return [
            'id' => $user->id,
            'role' => $profile?->role,
            'status' => $profile?->status ?? 'active',
            'must_change_password' => (bool) ($profile?->must_change_password ?? false),
            'name' => $user->name,
            'email' => $user->email,
            'phone' => $profile?->phone ?? '',
            'photo' => $profile?->photo ?? '',
            'bio' => $profile?->bio ?? '',
            'address' => $profile?->address ?? '',
            'social' => [
                'instagram' => $profile?->instagram ?? '',
                'facebook' => $profile?->facebook ?? '',
                'twitter' => $profile?->twitter ?? '',
                'tiktok' => $profile?->tiktok ?? '',
                'youtube' => $profile?->youtube ?? '',
                'linkedin' => $profile?->linkedin ?? '',
                'website' => $profile?->website ?? '',
                'github' => $profile?->github ?? '',
            ],
            'guru' => $user->guru ? [
                'nip' => $user->guru->nip ?? '',
                'nuptk' => $user->guru->nuptk ?? '',
                'teacher_id' => $user->guru->teacher_id ?? '',
                'subject' => $user->guru->subject ?? '',
                'position' => $user->guru->position ?? '',
                'achievements' => $user->guru->achievements ?? [],
                'certifications' => $user->guru->certifications ?? [],
            ] : null,
            'osis' => $user->osisAccount ? [
                'member_id' => $user->osisAccount->member_id ?? '',
                'nisn' => $user->osisAccount->nisn ?? '',
                'division' => $user->osisAccount->division ?? '',
                'position' => $user->osisAccount->position ?? '',
                'achievements' => $user->osisAccount->achievements ?? [],
                'work_programs' => $user->osisAccount->work_programs ?? [],
            ] : null,
            'student' => $user->student ? [
                'nisn' => $user->student->nisn ?? '',
                'class' => $user->student->class ?? '',
                'major' => $user->student->major ?? '',
                'gender' => $user->student->gender ?? '',
                'date_of_birth' => $user->student->date_of_birth?->toDateString() ?? '',
                'place_of_birth' => $user->student->place_of_birth ?? '',
                'address' => $user->student->address ?? '',
                'achievements' => $user->student->achievements ?? [],
            ] : null,
        ];
    }
}
