<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // Extend profiles with self-managed profile fields, account status and
        // the "must change password on next login" flag.
        Schema::table('profiles', function (Blueprint $table) {
            $table->text('photo')->default('')->after('email');
            $table->text('bio')->default('');
            $table->text('address')->default('');
            $table->text('instagram')->default('');
            $table->text('facebook')->default('');
            $table->text('twitter')->default('');
            $table->text('tiktok')->default('');
            $table->text('youtube')->default('');
            $table->text('linkedin')->default('');
            $table->text('website')->default('');
            $table->text('github')->default('');
            $table->string('status', 20)->default('active');
            $table->boolean('must_change_password')->default(false);
        });

        // GURU (teacher) account data. teacher_id is always generated by the
        // system; nip / nuptk are optional but unique when present.
        Schema::create('gurus', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->foreign('id')->references('id')->on('users')->onDelete('cascade');
            $table->string('nip', 50)->nullable()->unique();
            $table->string('nuptk', 50)->nullable()->unique();
            $table->string('teacher_id', 50)->unique();
            $table->text('subject')->default('');
            $table->text('position')->default('');
            $table->json('achievements')->default('[]');
            $table->json('certifications')->default('[]');
            $table->timestamps();
        });

        // OSIS member account data. member_id is always generated by the system;
        // nisn is optional (members can also log in with their NISN).
        Schema::create('osis_accounts', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->foreign('id')->references('id')->on('users')->onDelete('cascade');
            $table->string('member_id', 50)->unique();
            $table->string('nisn', 50)->nullable()->unique();
            $table->text('division')->default('');
            $table->text('position')->default('');
            $table->json('achievements')->default('[]');
            $table->json('work_programs')->default('[]');
            $table->timestamps();
        });

        // STUDENT: add achievements (karya/mading already tracked via mading_posts).
        Schema::table('students', function (Blueprint $table) {
            $table->json('achievements')->default('[]')->after('major');
        });
    }

    public function down(): void
    {
        Schema::table('students', function (Blueprint $table) {
            $table->dropColumn('achievements');
        });
        Schema::dropIfExists('osis_accounts');
        Schema::dropIfExists('gurus');
        Schema::table('profiles', function (Blueprint $table) {
            $table->dropColumn([
                'photo', 'bio', 'address',
                'instagram', 'facebook', 'twitter', 'tiktok',
                'youtube', 'linkedin', 'website', 'github',
                'status', 'must_change_password',
            ]);
        });
    }
};
